trydjango/src/accounts/urls.py
from accounts import views
from django.urls import path

urlpatterns = [
path('login/', views.login_view, name = 'login'),
path('signup/', views.signup_view, name = 'signup'),
path('register_success/', views.success_view, name = 'register_success')
]

trydjango/src/rus_urban/urls.py
from django.contrib import admin
from django.urls import path
from words.views import add_word_view, like_category, dislike_category
from pages import views
from django.urls import path, include
urlpatterns = [
    path('', views.home_view, name='home'),
    path('contacts/', views.contacts, name='contacts'),
    path('admin/', admin.site.urls),
    path('add/', add_word_view),
    path('output/', views.output, name='output'),
    path('accounts/', include('accounts.urls')),
    path('like_category/', like_category, name='like_category'),
    path('dislike_category/', dislike_category, name='dislike_category')
]

trydjango/src/words/models.py
from django.db import models
from django.template.defaultfilters import slugify
import datetime


# Create your models here.
class Word(models.Model):
    word        = models.CharField(max_length=100)
    definition  = models.TextField(null=True, blank=True, default="Definition")
    examples    = models.TextField(null=True, blank=True, default="Examples")
    updater     = models.CharField(max_length=100, default="anonym")
    city        = models.CharField(max_length=100, default="Moscow")
    date        = models.CharField(max_length=100, default=datetime.datetime.today().strftime("%Y-%m-%d-%H.%M.%S"))
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)

trydjango/src/words/forms.py
from django import forms
from .models import Word

class NewWord(forms.ModelForm):
	class Meta:
		model = Word
		fields = [
            'word',
            'definition',
            'examples',
            'city',
            'date'
		]

trydjango/src/words/views.py
from django.shortcuts import render
from .models import Word
from .forms import NewWord
from django.http import HttpResponse


def add_word_view(request, *args, **kwargs):
    form = NewWord(request.POST or None)
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = 'Anonymous'
    #form.updater = username
    if form.is_valid():
        newform = Word()
        newform.word = form.cleaned_data['word']
        newform.definition = form.cleaned_data['definition']
        newform.examples = form.cleaned_data['examples']
        newform.updater = username
        newform.city = form.cleaned_data['city']
        newform.date = form.cleaned_data['date']
        newform.save()
    context = {
    'form' : form,
    'username' : username
    }
    return render(request, 'add.html', context)


def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['word']
    likes = 0
    if cat_id:
        cat = Word.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes = likes
            cat.save()
    return HttpResponse(likes)


def dislike_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['word']
    dislikes = 0
    if cat_id:
        cat = Word.objects.get(id=int(cat_id))
        if cat:
            dislikes = cat.dislikes + 1
            cat.dislikes = dislikes
            cat.save()
    return HttpResponse(dislikes)

trydjango/src/words/templates/add.html
{% extends 'base.html' %}

{% block content %}
    <form method='POST'> {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <p style="margin-left:50px;">Добавить слово:</p>
        <p>
            <label for="id_word">Слово:</label>
            <input id="id_word" type="text" name="word" maxlength="100" placeholder="word" required/>
        </p>
        <p>
            <label for="id_definition">Определение:</label>
            <textarea id="id_definition" name="definition" placeholder="definition" required></textarea>
        </p>
        <p>
            <label for="id_examples">Примеры:</label>
            <textarea id="id_examples" name="examples" placeholder="examples" required></textarea>
        </p>
        <p>
            <label for="id_city">Город:</label>
            <input id="id_city" type="text" name="city" maxlength="100" placeholder="city" required/>
        </p>
        <p style="display:none;">
            <label for="id_date">Дата:</label>
            <input id="id_date" type="text" name="date" maxlength="100" placeholder="date" value='{% now "jS F Y H:i" %}'/>
        </p>
        <input type='submit' class="btn btn-success" value='Save'/>
    </form>
{% endblock %}